---
# get_url seems to be too stupid for following redirects
- name: Download raspbian-lite image to local machine
  shell:
    "curl -L -o {{ local_raspbian_image_archive }} https://downloads.raspberrypi.org/raspbian_lite_latest"
  args:
    creates: "{{ local_raspbian_image_archive }}"
    warn: no
  become: no
  delegate_to: 127.0.0.1

- name: Unzip local raspbian-lite image
  unarchive:
    src: "{{ local_raspbian_image_archive }}"
    dest: " {{ local_image_extract_path }}"
    creates: "{{ local_raspbian_image_archive }}"
  become: no
  delegate_to: 127.0.0.1

- name: Get name of unzipped image
  find:
    paths: "{{ local_image_extract_path }}"
    patterns: '*-lite.img'
  register: local_raspbian_image
  delegate_to: 127.0.0.1

# Enable ssh in raspbian-lite image
- name: Create loopback device
  shell:
    losetup --show -f -P {{ local_raspbian_image.files[0].path }}
  register: losetup_device
  delegate_to: 127.0.0.1

- name: Create mountpoint for image
  file:
    path: "{{ image_mountpoint }}"
    state: directory
  delegate_to: 127.0.0.1

- name: Mount image
  mount:
    path: "{{ image_mountpoint }}"
    src: "{{ losetup_device.stdout}}p1"
    fstype: vfat
    state: mounted
  delegate_to: 127.0.0.1

- name: Enable ssh in image
  file:
    path: "{{ image_mountpoint }}/ssh"
    state: touch
  delegate_to: 127.0.0.1

- name: Unmount Image
  mount:
    path: "{{ image_mountpoint }}"
    state: absent
  delegate_to: 127.0.0.1

- name: Detach loopback device
  shell:
    losetup -d {{ losetup_device.stdout }}
  args:
    removes: "{{ losetup_device.stdout }}"
  delegate_to: 127.0.0.1


- name: Zip modified image
  archive:
    path: "{{ local_raspbian_image.files[0].path }}"
    dest: "{{ local_raspbian_image_archive }}"
    format: zip
  delegate_to: 127.0.0.1

- name: Upload modified raspbian-lite image
  copy:
    src: "{{ local_raspbian_image_archive }}"
    dest: "{{ remote_raspbian_image_archive }}"

- name: Enable magic SysRQ
  shell:
    echo 1 > /proc/sys/kernel/sysrq

- name: Write image to disk
  shell:
    dd if={{remote_raspbian_image_archive }} bs=4M | funzip | dd bs=4M of=/dev/mmcblk0
# TODO
# wait for host to come up again
# login with pi user, add new user
# delete pi user
