---
- hosts: all
  remote_user: your-user
  become: yes
  vars:
    local_raspbian_image_archive: /path/to/raspbian-lite.zip
    local_image_extract_path: /path/to/whatever
    image_mountpoint: /mnt/raspbian
    remote_raspbian_image_archive: /tmp/raspbian-lite.zip
  roles:
    - reset-lab
