---
- name: Update system
  apt:
    upgrade: dist

- name: Install needed packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

# it's stupid to fetch a key via curl, but Docker doesn't seem to care to
# upload their keys to proper keyservers
- name: Add Docker Key
  shell:
    curl -fsSL https://download.docker.com/linux/raspbian/gpg | apt-key add -qq
  args:
    warn: no

- name: Determine Raspbian release
  shell:
    lsb_release -cs
  register: raspbian_release

- name: Add docker repos
  apt_repository:
    repo: "deb https://download.docker.com/linux/raspbian {{ raspbian_release.stdout }} edge"
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    install_recommends: no
    update_cache: yes

- name: Disable dphys-swapfile
  shell:
      dphys-swapfile swapoff && dphys-swapfile uninstall
  args:
    removes: /var/swap

- name: Disable dphys-swapfile service
  service:
    name: dphys-swapfile
    state: stopped
    enabled: no

- name: Enable cgroup settings
  lineinfile:
    dest=/boot/cmdline.txt
    backrefs=yes
    state=present
    regexp='(.*rootwait)$'
    line='\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  register: cgroups_changed

- name: Reboot the lab hosts
  reboot:
    reboot_timeout: 3600
  when: cgroups_changed.changed

- name: Add k8s repo key
  shell:
      curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -qq
  args:
    warn: no

- name: add k8s repo
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: Install kubeadm
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - kubeadm
    - kubectl
